export const LOAD_SEARCH_RESULT_REQUEST = "LOAD_SEARCH_RESULT_REQUEST";
export const LOAD_SEARCH_RESULT_SUCCESS = "LOAD_SEARCH_RESULT_SUCCESS";
export const LOAD_GROCERY_AUTOCOMPLETE_REQUEST =
  "LOAD_GROCERY_AUTOCOMPLETE_REQUEST";
export const LOAD_GROCERY_AUTOCOMPLETE_SUCCESS =
  "LOAD_GROCERY_AUTOCOMPLETE_SUCESS";
export const SAVE_GROCERY_ITEM_QUERY = "SAVE_GROCERY_ITEM_QUERY";
export const LOAD_GROCERY_SEARCH_RESULTS_WITH_STORE_SUCCESS =
  "LOAD_GROCERY_SEARCH_RESULTS_WITH_STORE_SUCCESS";
export const LOAD_GROCERY_SEARCH_RESULTS_WITH_STORE_REQUEST =
  "LOAD_GROCERY_SEARCH_RESULTS_WITH_STORE_REQUEST";
export const LOAD_BRAND_AUTOCOMPLETE_REQUEST = "LOAD_AUTOCOMPLETE_REQUEST";
export const LOAD_BRAND_CUSTOMPLETE_SUCCESS = "LOAD_BRAND_AUTOCOMPLETE_SUCCESS";
