export const LOAD_SEARCH_RESULT_REQUEST = "LOAD_SEARCH_RESULT_REQUEST";
export const LOAD_SEARCH_RESULT_SUCCESS = "LOAD_SEARCH_RESULT_SUCCESS";
export const LOAD_GROCERY_AUTOCOMPLETE_REQUEST =
  "LOAD_GROCERY_AUTOCOMPLETE_REQUEST";
export const LOAD_GROCERY_AUTOCOMPLETE_SUCCESS =
  "LOAD_GROCERY_AUTOCOMPLETE_SUCESS";
export const SAVE_GROCERY_ITEM_QUERY = "SAVE_GROCERY_ITEM_QUERY";
