export const LOAD_SEARCH_RESULT_REQUEST = "LOAD_SEARCH_RESULT_REQUEST";
export const LOAD_SEARCH_RESULT_SUCCESS = "LOAD_SEARCH_RESULT_SUCCESS";
export const LOAD_GROCERY_AUTOCOMPLETE_REQUEST =
	"LOAD_GROCERY_AUTOCOMPLETE_REQUEST";
export const LOAD_GROCERY_AUTOCOMPLETE_SUCCESS =
	"LOAD_GROCERY_AUTOCOMPLETE_SUCESS";
export const SAVE_GROCERY_ITEM_QUERY = "SAVE_GROCERY_ITEM_QUERY";
export const LOAD_GROCERY_SEARCH_RESULTS_WITH_STORE_SUCCESS =
	"LOAD_GROCERY_SEARCH_RESULTS_WITH_STORE_SUCCESS";
export const LOAD_GROCERY_SEARCH_RESULTS_WITH_STORE_REQUEST =
	"LOAD_GROCERY_SEARCH_RESULTS_WITH_STORE_REQUEST";
export const LOAD_BRAND_AUTOCOMPLETE_REQUEST = "LOAD_AUTOCOMPLETE_REQUEST";
export const LOAD_BRAND_AUTOCOMPLETE_SUCCESS =
	"LOAD_BRAND_AUTOCOMPLETE_SUCCESS";
export const LOAD_AISLE_AUTOCOMPLETE_REQUEST =
	"LOAD_AISLE_AUTOCOMPLETE_REQUEST";
export const LOAD_AISLE_AUTOCOMPLETE_SUCCESS =
	"LOAD_AISLE_AUTOCOMPLETE_SUCCESS";
export const SAVE_GROCERY_ITEM_IN_PROGRESS = "SAVE_GROCERY_ITEM_IN_PROGRESS";
export const SAVE_GROCERY_ITEM_SUCCESS = "SAVE_GROCERY_ITEM_SUCCESS";
export const USER_REGISTRATION_IN_PROGRESS = "USER_REGISTRATION_IN_PROGRESS";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_CATCH_ERROR = "USER_REGISTRATION_CATCH_ERROR";
export const LOAD_DISHES_REQUEST = "LOAD_DISHES_REQUEST";
export const LOAD_DISHES_SUCCESS = "LOAD_DISHES_SUCCESS";
export const USER_LOGIN_IN_PROGRESS = "LOAD_USER_LOG_IN_PROGRESS";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_ERROR = "USER_INFO_ERROR";
export const USER_INFO_PROGRESS = "USER_INFO_PROGRESS";
export const USER_INFO_TOKEN_ERROR = "USER_INFO_TOKEN_ERROR";
